version: '3.8'

services:
  mongo:
    image: mongo:8
    container_name: petgpt_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

  backend:
    build: ./backend
    container_name: petgpt_backend
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/petgpt
    depends_on:
      - mongo

volumes:
  mongo_data:
