version: '3.8'

services:
  mongo:
    image: mongo:8
    container_name: petgpt_mongo
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - petgpt_network

  backend:
    build: ./backend
    container_name: petgpt_backend
    ports:
      - "3001:3001"
    environment:
      - MONGO_URI=mongodb://mongo:27017/petgpt
    depends_on:
      - mongo
    networks:
      - petgpt_network
    labels:
      - "app.petgpt.service=backend"

  frontend:
    build: ./frontend
    container_name: petgpt_frontend
    ports:
      - "5173:80" # Changed to 5173 for Electron to connect in development
    depends_on:
      - backend
    networks:
      - petgpt_network
    labels:
      - "app.petgpt.service=frontend"

networks:
  petgpt_network:
    driver: bridge

volumes:
  mongo_data:
